-- AlterEnum
ALTER TYPE "TrustEventType" ADD VALUE IF NOT EXISTS 'EVENT_FEEDBACK_SUBMITTED';

-- AlterEnum
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'ACTIVITY_LOCATION_UPDATED';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'TRUST_RECALCULATED';
